###############################################################################
# 99_generate_todo_annex.R
#
# Purpose:
# Translate the human-readable TODO.md into a colored LaTeX to-do annex that is
# loaded as an appendix in the Overleaf paper (paper/sections/99_todo_annex.tex).
#
# Do NOT hand-edit paper/sections/99_todo_annex.tex. Edit TODO.md and rerun:
#   source("R/99_generate_todo_annex.R")
#
# Uses base R only (no pipeline dependency), so it can run standalone.
###############################################################################

todo_path  <- if (requireNamespace("here", quietly = TRUE)) {
  here::here("TODO.md")
} else {
  "TODO.md"
}
annex_path <- if (requireNamespace("here", quietly = TRUE)) {
  here::here("paper", "sections", "99_todo_annex.tex")
} else {
  "paper/sections/99_todo_annex.tex"
}

lines <- readLines(todo_path, warn = FALSE)

# Keep only markdown table rows (start with "|"), drop the header and separator.
table_rows <- lines[grepl("^\\s*\\|", lines)]
table_rows <- table_rows[!grepl("^\\s*\\|\\s*-+", table_rows)]        # separator
table_rows <- table_rows[!grepl("\\|\\s*Section\\s*\\|", table_rows)]  # header

split_row <- function(row) {
  cells <- strsplit(row, "|", fixed = TRUE)[[1]]
  cells <- trimws(cells)
  cells <- cells[cells != ""]
  cells
}

escape_tex <- function(x) {
  x <- gsub("\\", "\\textbackslash{}", x, fixed = TRUE)
  x <- gsub("&", "\\&", x, fixed = TRUE)
  x <- gsub("%", "\\%", x, fixed = TRUE)
  x <- gsub("#", "\\#", x, fixed = TRUE)
  x <- gsub("_", "\\_", x, fixed = TRUE)
  x
}

priority_tex <- function(p) {
  p <- tolower(trimws(p))
  col <- switch(p,
    "high"   = "red",
    "medium" = "orange",
    "low"    = "gray",
    "black"
  )
  sprintf("\\textcolor{%s}{%s}", col, escape_tex(tools::toTitleCase(p)))
}

status_tex <- function(s) {
  s <- tolower(trimws(s))
  switch(s,
    "done"        = "\\textcolor{ForestGreen}{$\\checkmark$ Done}",
    "in-progress" = "\\textcolor{orange}{$\\circ$ In progress}",
    "pending"     = "\\textcolor{gray}{$\\square$ Pending}",
    escape_tex(tools::toTitleCase(s))
  )
}

body <- character(0)
for (row in table_rows) {
  cells <- split_row(row)
  if (length(cells) < 5) next
  section  <- escape_tex(cells[1])
  id       <- escape_tex(cells[2])
  task     <- escape_tex(cells[3])
  priority <- priority_tex(cells[4])
  status   <- status_tex(cells[5])
  body <- c(body, sprintf("%s & %s & %s & %s & %s \\\\",
                          section, id, task, priority, status))
}

header <- c(
  "% AUTO-GENERATED by R/99_generate_todo_annex.R from TODO.md. Do not edit by hand.",
  "\\section{Project To-Do List}",
  "\\label{sec:todo-annex}",
  "\\footnotesize",
  "\\begin{longtable}{p{2.2cm} c p{6.5cm} c c}",
  "\\toprule",
  "\\textbf{Section} & \\textbf{\\#} & \\textbf{Task} & \\textbf{Priority} & \\textbf{Status} \\\\",
  "\\midrule",
  "\\endhead"
)

footer <- c(
  "\\bottomrule",
  "\\end{longtable}",
  "\\normalsize"
)

writeLines(c(header, body, footer), annex_path)
message("Wrote to-do annex: ", annex_path)
